[project]
name = "jilguedev-ansible"
version = "0.1.0"
description = ""
authors = [
    {name = "César M. Cristóbal",email = "cesar@callepuzzle.com"}
]
requires-python = ">=3.14"
dependencies = [
    "ansible (>=13.6.0,<14.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
