---
all:
  hosts:
    b2-restore-test:
      ansible_host: b2-restore-test
      ansible_connection: podman
      container_image: python:3.12-slim-bookworm
      container_command: sleep 3600
      borg_repo_path: /backup
      borg_passphrase_file: /repo/.borg.txt
      borg_archive_name: "20260806_040126-nextcloud-aio"
